---
- name: Setup Web Server
  hosts: all
  become: true
  become_method: sudo



  task:
  - name: Install Apache Server
    apt:
       name: apache2                                                            
       state: present

  - name: set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Install Git
    apt:
       name: git
       state: present

  - name: Install curl
    apt:
       name: curl
       state: present

  - name: Install ufw
    apt:
       name: ufw
       state: present


  - name: Install unzip
    apt:
       name: unzip
       state: present

  - name: Install wget
    apt:
       name: wget
       state: present

  - name: Install mysql
    apt:
       name: mysql-server
       state: latest

  - name: update "apt"
    apt:
      update_cache: yes
      autoclean: yes
      autoremove: yes

  - name: Install PHP
    apt:
      name: php8.1
      state: present
    tags: php

  - name: Install php dependencies
    apt:
      pkg:
        - libapache2-mod-php
        - php8.1-mysql
        - php8.1-common
        - php8.1-mysql
        - php8.1-xml
        - php8.1-xmlrpc
        - php8.1-curl
        - php8.1-gd
        - php8.1-imagick
        - php8.1-cli
        - php8.1-dev
        - php8.1-imap
        - php8.1-mbstring
        - php8.1-opcache
        - php8.1-soap
        - php8.1-zip
        - php8.1-intl
      state: present
    tags: php_dep
    async: 60
    poll: 60
